
package org.certificatic.medicamento.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MedicamentoServiceImplService", targetNamespace = "http://Service.Medicamento.certificatic.org/", wsdlLocation = "http://soaperickmedicamentos.herokuapp.com/MedicamentoService?wsdl")
public class MedicamentoServiceImplService
    extends Service
{

    private final static URL MEDICAMENTOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MEDICAMENTOSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName MEDICAMENTOSERVICEIMPLSERVICE_QNAME = new QName("http://Service.Medicamento.certificatic.org/", "MedicamentoServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://soaperickmedicamentos.herokuapp.com/MedicamentoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEDICAMENTOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        MEDICAMENTOSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public MedicamentoServiceImplService() {
        super(__getWsdlLocation(), MEDICAMENTOSERVICEIMPLSERVICE_QNAME);
    }

    public MedicamentoServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEDICAMENTOSERVICEIMPLSERVICE_QNAME, features);
    }

    public MedicamentoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, MEDICAMENTOSERVICEIMPLSERVICE_QNAME);
    }

    public MedicamentoServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEDICAMENTOSERVICEIMPLSERVICE_QNAME, features);
    }

    public MedicamentoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MedicamentoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MedicamentoService
     */
    @WebEndpoint(name = "MedicamentoServiceImplPort")
    public MedicamentoService getMedicamentoServiceImplPort() {
        return super.getPort(new QName("http://Service.Medicamento.certificatic.org/", "MedicamentoServiceImplPort"), MedicamentoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MedicamentoService
     */
    @WebEndpoint(name = "MedicamentoServiceImplPort")
    public MedicamentoService getMedicamentoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Service.Medicamento.certificatic.org/", "MedicamentoServiceImplPort"), MedicamentoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEDICAMENTOSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw MEDICAMENTOSERVICEIMPLSERVICE_EXCEPTION;
        }
        return MEDICAMENTOSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
