
package org.certificatic.medicamento.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MedicamentoService", targetNamespace = "http://Service.Medicamento.certificatic.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MedicamentoService {


    /**
     * 
     * @return
     *     returns java.util.List<org.certificatic.medicamento.service.Medicamento>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerTodos", targetNamespace = "http://Service.Medicamento.certificatic.org/", className = "org.certificatic.medicamento.service.ObtenerTodos")
    @ResponseWrapper(localName = "obtenerTodosResponse", targetNamespace = "http://Service.Medicamento.certificatic.org/", className = "org.certificatic.medicamento.service.ObtenerTodosResponse")
    public List<Medicamento> obtenerTodos();

    /**
     * 
     * @param arg0
     * @return
     *     returns org.certificatic.medicamento.service.Medicamento
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearMedicamento", targetNamespace = "http://Service.Medicamento.certificatic.org/", className = "org.certificatic.medicamento.service.CrearMedicamento")
    @ResponseWrapper(localName = "crearMedicamentoResponse", targetNamespace = "http://Service.Medicamento.certificatic.org/", className = "org.certificatic.medicamento.service.CrearMedicamentoResponse")
    public Medicamento crearMedicamento(
        @WebParam(name = "arg0", targetNamespace = "")
        Medicamento arg0);

}
